import { NextResponse } from "next/server";
import { createPrismaClient } from "@/lib/create-prisma-client";
import {
  generateUniqueSalonSlug,
  slugifySalonName,
} from "@/lib/salon-slug";

function authorizeCron(request: Request) {
  const secret = process.env.CRON_SECRET;
  if (!secret) return true;
  return request.headers.get("authorization") === `Bearer ${secret}`;
}

export async function GET(request: Request) {
  if (!authorizeCron(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const prisma = createPrismaClient();
  const updates: string[] = [];

  try {
    await prisma.$executeRawUnsafe(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = 'Salon' AND column_name = 'slug'
        ) THEN
          ALTER TABLE "Salon" ADD COLUMN "slug" TEXT;
          UPDATE "Salon" SET "slug" = 'salon-' || REPLACE("id", '-', '') WHERE "slug" IS NULL;
          ALTER TABLE "Salon" ALTER COLUMN "slug" SET NOT NULL;
          CREATE UNIQUE INDEX "Salon_slug_key" ON "Salon"("slug");
        END IF;
      END $$;
    `);

    const salons = await prisma.salon.findMany({
      select: { id: true, name: true, slug: true },
      orderBy: { createdAt: "asc" },
    });

    for (const salon of salons) {
      const expectedSlug = slugifySalonName(salon.name);
      const looksAutoGenerated = salon.slug.startsWith("salon-");

      if (!looksAutoGenerated && salon.slug === expectedSlug) {
        continue;
      }

      const slug = await generateUniqueSalonSlug(salon.name, prisma, salon.id);
      await prisma.salon.update({ where: { id: salon.id }, data: { slug } });
      updates.push(`${salon.name} -> ${slug}`);
    }

    const testSalon = await prisma.salon.findFirst({
      where: { name: { equals: "Test Salon", mode: "insensitive" } },
      select: { id: true, slug: true },
    });

    if (testSalon && testSalon.slug !== "test-salon") {
      const conflict = await prisma.salon.findUnique({ where: { slug: "test-salon" } });
      if (conflict && conflict.id !== testSalon.id) {
        const moved = await generateUniqueSalonSlug(conflict.name, prisma, conflict.id);
        await prisma.salon.update({
          where: { id: conflict.id },
          data: { slug: moved },
        });
        updates.push(`${conflict.name} reassigned -> ${moved}`);
      }

      await prisma.salon.update({
        where: { id: testSalon.id },
        data: { slug: "test-salon" },
      });
      updates.push("Test Salon -> test-salon");
    }

    return NextResponse.json({ ok: true, updates });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ ok: false, error: message }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}
