import "dotenv/config";
import { createPrismaClient } from "../src/lib/create-prisma-client";
import {
  generateUniqueSalonSlug,
  slugifySalonName,
} from "../src/lib/salon-slug";

const prisma = createPrismaClient();

async function main() {
  const salons = await prisma.salon.findMany({
    select: { id: true, name: true, slug: true },
    orderBy: { createdAt: "asc" },
  });

  for (const salon of salons) {
    const looksAutoGenerated = salon.slug.startsWith("salon-");
    const expectedSlug = slugifySalonName(salon.name);

    if (!looksAutoGenerated && salon.slug === expectedSlug) {
      continue;
    }

    const slug = await generateUniqueSalonSlug(salon.name, prisma, salon.id);
    await prisma.salon.update({
      where: { id: salon.id },
      data: { slug },
    });
    console.log(`${salon.name} -> ${slug}`);
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
